### ISSUE TITLE
Tests do not currently pass

### ISSUE THREAD

**Issue by keeb-zz** [alunduil/margarine#11]
```
======================================================================
ERROR: Failure: ArgumentError (argument --flask-host: conflicting option string(s): --flask-host)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/website/margarine/tinge/__init__.py", line 65, in <module>
    "help": "Enable debugging of the flask application.",
  File "/website/margarine/parameters.py", line 163, in __init__
    self._add_argument_parameters(name, parameters)
  File "/website/margarine/parameters.py", line 327, in _add_argument_parameters
    parser.add_argument(*options["args"], **options["kwargs"])
  File "/usr/lib/python2.7/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
ArgumentError: argument --flask-host: conflicting option string(s): --flask-host

======================================================================
ERROR: Failure: ImportError (No module named api)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/website/test_margarine/test_unit/test_api/test_article.py", line 13, in <module>
    from margarine.api import information
ImportError: No module named api

======================================================================
ERROR: Failure: ImportError (No module named api)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/website/test_margarine/test_unit/test_api/test_user.py", line 12, in <module>
    from margarine.api import information
ImportError: No module named api

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (test_users.py, line 50))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/website/test_margarine/test_unit/test_consumers/test_users.py", line 50
    self.mock_keyspace.setex.assert_called_once_with(mock.ANY, "test_user", mock.ANY)
       ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 20 tests in 1.023s

FAILED (errors=5)
```

**Comment by keeb-zz** [comment]
Forgot one..

`````` ======================================================================
ERROR: Failure: ImportError (No module named bs4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/keeb/websites/margarine/virtualenv/local/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/keeb/websites/margarine/virtualenv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/keeb/websites/margarine/virtualenv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/keeb/websites/margarine/margarine/consumers/__init__.py", line 16, in <module>
    from margarine.consumers import articles
  File "/home/keeb/websites/margarine/margarine/consumers/articles.py", line 13, in <module>
    import bs4
ImportError: No module named bs4
-------------------- >> begin captured logging << --------------------```
``````

**Comment by alunduil** [comment]
Hey Nick,

Thanks for reporting this.  I've been working on refactoring and fixing the test suite but haven't put an issue in for this yet.  Once we've got them working again you'll be able to help us verify the correctness and accuracy by checking out the test/refactor branch.

If you want to help design the new test suite I'd love to hear any idea or input you might have.

The last failing test you submitted is actually due to beautifulsoup4 not being installed rather than the test suite itself.

Regards,

Alex Brandt

**Comment by keeb-zz** [comment]
@alunduil thanks for the quick response. I'd love to help.

I'm currently at a place where I have fixed a lot of the problems in the tests (I have them all running, but 14 errors and 3 failures) but am missing a key piece of code in `margarine.api`. 

Is this in another branch that I can pull?

**Comment by keeb-zz** [comment]
Ah, I've answered my own question by taking a look at the test refactor branch.

**Comment by alunduil** [comment]
I'm sorry, I forgot to comment on that.  I actually moved the margarine.api module to margarine.blend so the module names would map to the daemon names.  I plan on doing the same with margarine.consumers → margarine.spread as well.

Let me know if there is anything else and I'll continue working on making the test suite more robust.

**Comment by alunduil** [comment]
I've gone through and added several test cases as well as refactored major portions.  Does anyone mind taking a peek and providing any feedback before I merge to master and fix the remaining test and code problems?

**Comment by alunduil** [comment]
Moving this discussion to issue 21 and marking this bug as invalid unless there are objections.
