### ISSUE TITLE
User Update Property Merge

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#17]
Currently the properties are not merged on a user update request but they could be potentially overcoming limitations with updates.  The test showing this type of message composition:

```
======================================================================
FAIL: User Update—Submitted,Complete,Authorized
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_blend/test_user.py", line 180, in test_user_update_submitted_complete_authorized
    routing_key = 'users.update',
  File "/usr/lib64/python2.7/site-packages/mock.py", line 846, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: basic_publish(body='{"username": "alunduil", "requested_username": "alunduil", "email": "alunduil@alunduil.com"}', exchange='margarine.users.topic', routing_key='users.update', properties=<ANY>)
Actual call: basic_publish(body='{"username": "alunduil", "original_username": "alunduil", "email": null, "name": "Alex Brandt"}', exchange='margarine.users.topic', properties=<BasicProperties(['durable=False', 'content_type=application/json'])>, routing_key='users.update')
-------------------- >> begin captured logging << --------------------
margarine.blend.user: DEBUG: user: {'username': 'alunduil', '_id': ObjectId('5201aae24ee7ca5b8c996ef3'), 'email': 'alunduil@alunduil.com'}
margarine.blend.user: DEBUG: X-Auth-Token: c2d52150-08d1-4ae3-b19c-323c9e37813d
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
Looks like the test makes an incorrect assumption as you can see from commit 884adc8a4c5d72df380e906ec2b3edeadb552ba0.

**Comment by hhoover** [comment]
merged
