### ISSUE TITLE
spread config file integer

### ISSUE THREAD

**Issue by jruels** [alunduil/margarine#2]
root@spread:/srv/www/margarine# PYTHONPATH="/srv/www/margarine" bin/spread
No handlers could be found for logger "margarine.parameters"
Traceback (most recent call last):
  File "bin/spread", line 11, in <module>
    margarine.consumers.main()
  File "/srv/www/margarine/margarine/consumers/**init**.py", line 33, in main
    channel = get_channel()
  File "/srv/www/margarine/margarine/communication.py", line 83, in get_channel
    credentials = credentials
  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 56, in **init**
    raise TypeError("Port must be an int")
TypeError: Port must be an int

**Comment by alunduil** [comment]
Looks like this is due to the old version of pika.  We'll have to change the dependency to be on pika >= 0.9.12.

**Comment by alunduil** [comment]
Fixed in commit 22ecf8f.
