### ISSUE TITLE
Deduplicate Requirements

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#23]
The requirements for margarine are currently listed in `requirements.txt` and `setup.py`.  They should be imported into `setup.py` to increase re-use.

**Comment by alunduil** [comment]
Excellent resource on setuptools internals: http://peak.telecommunity.com/DevCenter/setuptools

**Comment by alunduil** [comment]
Switching package system to setuptools per http://stackoverflow.com/questions/6344076/differences-between-distribute-distutils-setuptools-and-distutils2/14753678#14753678

**Comment by alunduil** [comment]
This should be ready for review.  Test installs should be done as well as design of automated builds (with PyPI pushes).  I'll start working on a live ebuild to hit this branch and test as well to find any issues with the installation.

**Comment by alunduil** [comment]
Looks like the setuptools build tries to interpolate the nosetests section of setup.cfg:

```
alunduil@elijah alunduil-overlay % ebuild www-apps/margarine/margarine-9999.ebuild clean test install
Appending /home/alunduil/Projects/gentoo/alunduil-overlay to PORTDIR_OVERLAY...
Forcing test.
 * checking ebuild checksums ;-) ...                                                                                                                                                                                                                                     [ ok ]
>>> Unpacking source...
GIT update -->
   repository:               git://github.com/raxsavvy/margarine.git
   at the commit:            721c527382f9fe24da850420675a729842e695c8
   branch:                   issues/23
   storage directory:        "/usr/portage/distfiles/egit-src/margarine.git"
   checkout type:            bare repository
Cloning into '/var/tmp/portage/www-apps/margarine-9999/work/margarine-9999'...
done.
Checking connectivity... done
Branch branch-issues/23 set up to track remote branch issues/23 from origin.
Switched to a new branch 'branch-issues/23'
>>> Unpacked to /var/tmp/portage/www-apps/margarine-9999/work/margarine-9999
>>> Source unpacked in /var/tmp/portage/www-apps/margarine-9999/work
>>> Preparing source in /var/tmp/portage/www-apps/margarine-9999/work/margarine-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/www-apps/margarine-9999/work/margarine-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/www-apps/margarine-9999/work/margarine-9999 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build --build-base /var/tmp/portage/www-apps/margarine-9999/work/margarine-9999-python2_7 --build-platlib /var/tmp/portage/www-apps/margarine-9999/work/margarine-9999-python2_7/lib --build-purelib /var/tmp/portage/www-apps/margarine-9999/work/margarine-9999-python2_7/lib --build-scripts /var/tmp/portage/www-apps/margarine-9999/work/margarine-9999-python2_7/scripts
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    setup(**PARAMS)
  File "/usr/lib64/python2.7/distutils/core.py", line 125, in setup
    dist.parse_config_files()
  File "/usr/lib64/python2.7/distutils/dist.py", line 397, in parse_config_files
    val = parser.get(section,opt)
  File "/usr/lib64/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib64/python2.7/ConfigParser.py", line 669, in _interpolate
    option, section, rawval, e.args[0])
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
        section: [nosetests]
        option : logging-format
        key    : pathname
        rawval : %(pathname)s:%(lineno)d: %(process)d: %(message)s

 * ERROR: www-apps/margarine-9999::alunduil-overlay failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_compile
 *   environment, line 3797:  Called distutils-r1_src_compile
 *   environment, line  980:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  301:  Called python_parallel_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 3674:  Called multibuild_parallel_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2917:  Called multibuild_foreach_variant '_multibuild_parallel' '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2865:  Called _multibuild_run '_multibuild_parallel' '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2863:  Called _multibuild_parallel '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2908:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  644:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line  969:  Called distutils-r1_python_compile
 *   environment, line  871:  Called esetup.py
 *   environment, line 1752:  Called die
 * The specific snippet of code:
 *       "${@}" || die
 * 
 * If you need support, post the output of `emerge --info '=www-apps/margarine-9999::alunduil-overlay'`,
 * the complete build log and the output of `emerge -pqv '=www-apps/margarine-9999::alunduil-overlay'`.
 * The complete build log is located at '/var/tmp/portage/www-apps/margarine-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-apps/margarine-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/www-apps/margarine-9999/work/margarine-9999'
 * S: '/var/tmp/portage/www-apps/margarine-9999/work/margarine-9999'
```

**Comment by dubsquared** [comment]
Are we just looking for input on setup.py installation of Margarine here?  Can you elaborate on the ebuild process and how we can interact?

**Comment by alunduil** [comment]
Yep, just some feedback on the installation (and by extension pip) mechanism, setup.py.  The ebuild process is just write an ebuild and run it.  Currently, it doesn't build and I haven't taken the time to track down why.  The ebuild can be viewed at https://github.com/alunduil/alunduil-overlay/blob/www-apps/margarine/www-apps/margarine/margarine-9999.ebuild

As far as interaction with the ebuild process.  The easiest way would be to grab my overlay and then run the ebuild: `ebuild margarine-9999.ebuild clean install`

Otherwise, just seeing if the installation works and what if anything doesn't work is the more important thing.

**Comment by alunduil** [comment]
Upstream bug with nose filed: https://github.com/nose-devs/nose/issues/733

Still not convinced the bug is with them and not distutils but we'll see where this takes us.

**Comment by alunduil** [comment]
Is monkey patching an acceptable solution to this issue?

**Comment by dubsquared** [comment]
We'd have to (I think) submit an upstream patch nose and I'm not sure that's going to be the cleanest (see: fastest) solution.  Let's just roll with a monkey patch to preserve our expected output and reopen if it becomes an issues in the future.

**Comment by alunduil** [comment]
Needs a review for clearness of the code changed as well as review that the build and test invocations are something we're all happy with.  Otherwise, if it builds on your platform consider it an up vote and we're one step closer to getting a cheese shop package out.

**Comment by hhoover** [comment]
looks good, merged.
