### ISSUE TITLE
Handle Path Components in URI

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#34]
```
======================================================================
FAIL: URI—6 Components
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_helpers.py", line 209, in test_uri_components_6
    self._verify_uri(uri, components)
  File "test_margarine/test_unit/test_helpers.py", line 58, in _verify_uri
    self.assertEqual(component, value)
AssertionError: '/example/index.html' != '/example'
```

**Comment by alunduil** [comment]
```
======================================================================
FAIL: URI—5 Components
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_helpers.py", line 193, in test_uri_components_5
    self._verify_uri(uri, components)
  File "test_margarine/test_unit/test_helpers.py", line 58, in _verify_uri
    self.assertEqual(component, value)
AssertionError: '/example/index.html' != '/example'
```

**Comment by alunduil** [comment]
```
======================================================================
FAIL: URI—4 Components
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_helpers.py", line 171, in test_uri_components_4
    self._verify_uri(uri, components)
  File "test_margarine/test_unit/test_helpers.py", line 58, in _verify_uri
    self.assertEqual(component, value)
AssertionError: '/example/index.html' != '/example'
```

**Comment by alunduil** [comment]
```
======================================================================
FAIL: URI—3 Components
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_helpers.py", line 143, in test_uri_components_3
    self._verify_uri(uri, components)
  File "test_margarine/test_unit/test_helpers.py", line 58, in _verify_uri
    self.assertEqual(component, value)
AssertionError: '/example/index.html' != '/example'
```

**Comment by alunduil** [comment]
```
======================================================================
FAIL: URI—2 Components
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_helpers.py", line 115, in test_uri_components_2
    self._verify_uri(uri, components)
  File "test_margarine/test_unit/test_helpers.py", line 58, in _verify_uri
    self.assertEqual(component, value)
AssertionError: '/example/index.html' != '/example'
```

**Comment by alunduil** [comment]
The failing tests should be passing now.  Full URI parsing (query parameters, anchors, &c) are not handled yet but basic parsing is working.

**Comment by jruels** [comment]
success.

**Comment by jruels** [comment]
Docstring on URI helper needs "what does this thing do?" clarification.

**Comment by alunduil** [comment]
Per today's discussion these changes are acceptable and will be merged.
