### ISSUE TITLE
Change original_username to requested_username in Blend::User Update

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#35]
```
======================================================================
FAIL: Blend::User Update—Submitted,Complete,Authorized
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_blend/test_user.py", line 179, in test_user_update_submitted_complete_authorized
    routing_key = 'users.update',
  File "/usr/lib64/python2.7/site-packages/mock.py", line 846, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: basic_publish(body='{"username": "alunduil", "requested_username": "alunduil", "email": "alunduil@alunduil.com"}', exchange='margarine.users.topic', routing_key='users.update', properties=<ANY>)
Actual call: basic_publish(body='{"username": "alunduil", "original_username": "alunduil", "email": null, "name": "Alex Brandt"}', exchange='margarine.users.topic', properties=<BasicProperties(['durable=False', 'content_type=application/json'])>, routing_key='users.update')
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 11704: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 11704: mock_mask: set(['container'])
test_margarine/test_unit/__init__.py:94: 11704: to_mock: set(['keyspace', 'channel', 'collection'])
/home/alunduil/Projects/savvy/margarine/margarine/blend/user.py:208: 11704: user: {'username': 'alunduil', '_id': ObjectId('52265dbe4ee7ca2db8456cb7'), 'email': 'alunduil@alunduil.com'}
/home/alunduil/Projects/savvy/margarine/margarine/blend/user.py:227: 11704: X-Auth-Token: c2d52150-08d1-4ae3-b19c-323c9e37813d
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
Looks like #17 solves this issue.  Closing this bug as a duplicate.
