### ISSUE TITLE
Spurious name in body of message for Blend::User Create

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#36]
```
======================================================================
FAIL: Blend::User Create—Unsubmitted
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_blend/test_user.py", line 69, in test_user_create_unsubmitted
    routing_key = 'users.create',
  File "/usr/lib64/python2.7/site-packages/mock.py", line 846, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: basic_publish(body='{"username": "alunduil", "email": "alunduil@alunduil.com"}', exchange='margarine.users.topic', routing_key='users.create', properties=<ANY>)
Actual call: basic_publish(body='{"username": "alunduil", "email": "alunduil@alunduil.com", "name": null}', exchange='margarine.users.topic', properties=<BasicProperties(['durable=False', 'content_type=application/json'])>, routing_key='users.create')
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 11704: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 11704: mock_mask: set(['container'])
test_margarine/test_unit/__init__.py:94: 11704: to_mock: set(['keyspace', 'channel', 'collection'])
/home/alunduil/Projects/savvy/margarine/margarine/blend/user.py:208: 11704: user: None
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
Looks like this is commented upon in #17.  Closing this bug as a duplicate.
