### ISSUE TITLE
Incorrect Message Body in Spread::User Update Test

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#37]
```
======================================================================
ERROR: Spread::User Update
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_users.py", line 132, in test_user_update
    update_user_consumer(mock.MagicMock(), self.method, None, json.dumps(modifications[username]))
  File "/home/alunduil/Projects/savvy/margarine/margarine/spread/users.py", line 58, in update_user_consumer
    user.pop("username")
KeyError: 'username'
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 11704: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 11704: mock_mask: set(['container', 'channel'])
test_margarine/test_unit/__init__.py:94: 11704: to_mock: set(['keyspace', 'collection'])
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
This is related to #17 and should be based on the changes performed in that branch.  Thus, this will wait until that has been merged.

**Comment by alunduil** [comment]
Merged.
