### ISSUE TITLE
Typo in Spread::User Create—Submitted,Complete

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#38]
```
======================================================================
ERROR: Spread::User Create—Submitted,Complete
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_users.py", line 91, in test_user_create_submitted_complete
    for username, properties in self.account.iteritems():
AttributeError: 'SpreadUserCreateTest' object has no attribute 'account'
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 11704: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 11704: mock_mask: set(['container', 'channel'])
test_margarine/test_unit/__init__.py:94: 11704: to_mock: set(['keyspace', 'collection'])
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
After fixing the typo of account the test is now failing with the following message:

```
======================================================================
ERROR: Spread::User Create—Submitted,Complete
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_users.py", line 101, in test_user_create_submitted_complete
    create_user_consumer(*args)
  File "/home/alunduil/Projects/savvy/margarine/margarine/spread/users.py", line 36, in create_user_consumer
    get_collection("users").insert(user) # TODO Fix race condition of multiple sign-ups.
  File "/usr/lib64/python2.7/site-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 1010, in _mock_call
    raise effect
TypeError: __init__() takes at least 2 arguments (1 given)
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 31653: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 31653: mock_mask: set(['container', 'channel'])
test_margarine/test_unit/__init__.py:94: 31653: to_mock: set(['keyspace', 'collection'])
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
Looks like the problem is missing parameters for DuplicateKeyError on line 92.  Need to determine what values should be raised in a normal duplicate error in this context.

**Comment by alunduil** [comment]
After adding missing parameters, the test is failing due to the consumer continuing to run:

```
======================================================================
ERROR: Spread::User Create—Submitted,Complete
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_users.py", line 101, in test_user_create_submitted_complete
    create_user_consumer(*args)
  File "/home/alunduil/Projects/savvy/margarine/margarine/spread/users.py", line 42, in create_user_consumer
    password_email_consumer(channel, method, header, body)
  File "/home/alunduil/Projects/savvy/margarine/margarine/spread/users.py", line 77, in password_email_consumer
    user = get_collection("users").find_one({ "username": user["username"] })
KeyError: 'username'
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 11044: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 11044: mock_mask: set(['container', 'channel'])
test_margarine/test_unit/__init__.py:94: 11044: to_mock: set(['keyspace', 'collection'])
/home/alunduil/Projects/savvy/margarine/margarine/spread/users.py:38: 11044: E11000 duplicate key error index: production.users.$username_1  dup key: { : "alunduil" }
Traceback (most recent call last):
  File "/home/alunduil/Projects/savvy/margarine/margarine/spread/users.py", line 36, in create_user_consumer
    get_collection("users").insert(user) # TODO Fix race condition of multiple sign-ups.
  File "/usr/lib64/python2.7/site-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 1010, in _mock_call
    raise effect
DuplicateKeyError: E11000 duplicate key error index: production.users.$username_1  dup key: { : "alunduil" }
/home/alunduil/Projects/savvy/margarine/margarine/spread/users.py:39: 11044: Duplicate user request ignored!
--------------------- >> end captured logging << ---------------------
```

Should we log a shorter error message here rather than the full trace?  Also, the message should be acknowledged as handled (skipped due to duplicate).  How can we provide feedback about this error condition?  One more argument for making the user management stuff synchronous.  Will place a fix in this issue but think this needs a touch more discussion.

**Comment by alunduil** [comment]
Looks like this one is ready for review and question answering.  The test is now passing but is the test actually accomplishing what we want it to?

**Comment by alunduil** [comment]
Merged.
