### ISSUE TITLE
Missing iteritems call in Spread::User Password Email

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#39]
```
======================================================================
ERROR: Spread::User Password Email
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_users.py", line 146, in test_user_password_email
    for username, properties in self.accounts:
ValueError: too many values to unpack
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 11704: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 11704: mock_mask: set(['container', 'channel'])
test_margarine/test_unit/__init__.py:94: 11704: to_mock: set(['keyspace', 'collection'])
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
After adding the iteritems call, the test is failing due to a missing mock message:

```
======================================================================
ERROR: Spread::User Password Email
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_users.py", line 147, in test_user_password_email
    password_email_consumer(mock.MagicMock(), self.method, None, json.dumps(properties))
  File "/home/alunduil/Projects/savvy/margarine/margarine/spread/users.py", line 77, in password_email_consumer
    user = get_collection("users").find_one({ "username": user["username"] })
KeyError: 'username'
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 17670: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 17670: mock_mask: set(['container', 'channel'])
test_margarine/test_unit/__init__.py:94: 17670: to_mock: set(['keyspace', 'collection'])
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
After fixing the message passed to this particular test scenario, it has found another issue with the email sending mechanism:

```
======================================================================
ERROR: Spread::User Password Email
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_users.py", line 157, in test_user_password_email
    password_email_consumer(mock.MagicMock(), self.method, None, json.dumps(_))
  File "/home/alunduil/Projects/savvy/margarine/margarine/spread/users.py", line 83, in password_email_consumer
    send_user_email(user, verification)
  File "/home/alunduil/Projects/savvy/margarine/margarine/communication.py", line 153, in send_user_email
    message["To"] = "{user[name]} <{user[email]}>".format(user = user)
KeyError: 'name'
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 13952: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 13952: mock_mask: set(['container', 'channel'])
test_margarine/test_unit/__init__.py:94: 13952: to_mock: set(['keyspace', 'collection'])
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:137: 13952: len(parameters): 0
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:138: 13952: parsed? False
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:288: 13952: Adding parameters to default.
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:289: 13952: parameters: ()
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:227: 13952: Parsing Configuration Files
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:337: 13952: Parameters not parsed.
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:339: 13952: Searching for key: server.name
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:347: 13952: default: elijah.alunduil.com
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:349: 13952: Checking Environment
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:357: 13952: environ_key: __MAIN__.PY_SERVER_NAME
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:361: 13952: value: elijah.alunduil.com
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:363: 13952: Checking Configuration File
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:365: 13952: self._configuration_files: {'/etc/margarine/margarine.ini': <ConfigParser.SafeConfigParser instance at 0x35aa1b8>}
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:372: 13952: type(configuration_file): <type 'instance'>
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:373: 13952: configuration_file: <ConfigParser.SafeConfigParser instance at 0x35aa1b8>
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:382: 13952: value: elijah.alunduil.com
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:384: 13952: Checking CLI Arguments
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:388: 13952: self.arguments.server_name: None
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:398: 13952: value: elijah.alunduil.com
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:137: 13952: len(parameters): 0
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:138: 13952: parsed? False
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:288: 13952: Adding parameters to default.
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:289: 13952: parameters: ()
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:227: 13952: Parsing Configuration Files
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:337: 13952: Parameters not parsed.
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:339: 13952: Searching for key: email.from
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:347: 13952: default: noreply@elijah.alunduil.com
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:349: 13952: Checking Environment
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:357: 13952: environ_key: __MAIN__.PY_EMAIL_FROM
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:361: 13952: value: noreply@elijah.alunduil.com
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:363: 13952: Checking Configuration File
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:365: 13952: self._configuration_files: {'/etc/margarine/margarine.ini': <ConfigParser.SafeConfigParser instance at 0x35aa1b8>}
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:372: 13952: type(configuration_file): <type 'instance'>
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:373: 13952: configuration_file: <ConfigParser.SafeConfigParser instance at 0x35aa1b8>
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:382: 13952: value: noreply@elijah.alunduil.com
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:384: 13952: Checking CLI Arguments
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:388: 13952: self.arguments.email_from: noreply@elijah.alunduil.com
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:393: 13952: argument_value: noreply@elijah.alunduil.com
/home/alunduil/Projects/savvy/margarine/margarine/parameters.py:398: 13952: value: noreply@elijah.alunduil.com
--------------------- >> end captured logging << ---------------------
```

Will update those accesses to gets so we can use empty strings as the default values.

**Comment by alunduil** [comment]
Test is now passing but needs the fixture from #46 in order to be truly fixed.  Right now the test is not a proper unit and has side effects.  Let me know if the test needs anything else or if we should merge and fix other issues and schedule a test review for later.

**Comment by alunduil** [comment]
Merged.
