### ISSUE TITLE
Missing iteritems call in Spread::User Password Change

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#40]
```
======================================================================
ERROR: Spread::User Password Change
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_users.py", line 160, in test_user_password_change
    for username, properties in self.accounts:
ValueError: too many values to unpack
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 11704: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 11704: mock_mask: set(['container', 'channel'])
test_margarine/test_unit/__init__.py:94: 11704: to_mock: set(['keyspace', 'collection'])
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
After adding iteritems this test is now failing due to being an unimplemented stub:

```
======================================================================
FAIL: Spread::User Password Change
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_users.py", line 161, in test_user_password_change
    self.fail('Complete Stub!')
AssertionError: Complete Stub!
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 27942: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 27942: mock_mask: set(['container', 'channel'])
test_margarine/test_unit/__init__.py:94: 27942: to_mock: set(['keyspace', 'collection'])
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
This will be implemented as part of the test review and is thus waiting on that at which point this issue will be used to review the story and ensure it meets expectations.

**Comment by alunduil** [comment]
Merged and solved.
