### ISSUE TITLE
JSONify datetime in Spread::Article Create—Submitted,Incomplete - Sanitization Test

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#41]
```
======================================================================
ERROR: Spread::Article Create—Submitted,Incomplete - Sanitization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_articles.py", line 176, in test_article_create_submitted_incomplete_sanitization
    create_article_consumer(mock.MagicMock(), self.method, None, json.dumps(article))
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2013, 8, 7, 20, 25, 41, 596627) is not JSON serializable
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 11704: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 11704: mock_mask: set(['keyspace'])
test_margarine/test_unit/__init__.py:94: 11704: to_mock: set(['container', 'channel', 'collection'])
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
Currently, we're using BSON's json_util module to handle this but when we go datastore agnostic we'll want to start looking at solutions like the following:

http://stackoverflow.com/questions/455580/json-datetime-between-python-and-javascript

Also, we need to move queue messages into a native format and out of a JSON format completely.

**Comment by alunduil** [comment]
After fixing the JSONification issue it appears the message mock has too many elements:

```
======================================================================
FAIL: Spread::Article Create—Submitted,Incomplete - Sanitization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_articles.py", line 182, in test_article_create_submitted_incomplete_sanitization
    self._validate_mocks(_id, article)
  File "test_margarine/test_unit/test_spread/test_articles.py", line 57, in _validate_mocks
    self.mock_collection.update.assert_called_once_with({ '_id': _id }, { '$set': article }, upsert = True)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 846, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: update({'_id': '44d85795248d5899b8caac2bd8233755'}, {'$set': {'text_object_name': '248d-5899-b8ca-ac2bd8233755', 'url': 'http://blog.alunduil.com/posts/an-explanation-of-lvm-snapshots.html', 'created_at': datetime.datetime(2013, 8, 7, 20, 25, 41, 596627), 'text_container_name': '44d85795', 'etag': 'bf6285d832a356e1bf509a63edc8870f', 'parsed_at': datetime.datetime(2013, 8, 7, 20, 25, 41, 596627), 'size': 31052}}, upsert=True)
Actual call: update({'_id': u'44d85795248d5899b8caac2bd8233755'}, {'$set': {u'created_at': {u'$date': 1375907141596}, u'parsed_at': {u'$date': 1375907141596}}}, upsert=True)
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 3622: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 3622: mock_mask: set(['keyspace'])
test_margarine/test_unit/__init__.py:94: 3622: to_mock: set(['container', 'channel', 'collection'])
/home/alunduil/Projects/savvy/margarine/margarine/spread/articles.py:53: 3622: article: {u'text_object_name': u'248d-5899-b8ca-ac2bd8233755', u'url': u'http://blog.alunduil.com/posts/an-explanation-of-lvm-snapshots.html', u'created_at': {u'$date': 1375907141596}, u'text_container_name': u'44d85795', u'etag': u'bf6285d832a356e1bf509a63edc8870f', u'_id': u'44d85795248d5899b8caac2bd8233755', u'parsed_at': {u'$date': 1375907141596}, u'size': 31052}
/home/alunduil/Projects/savvy/margarine/margarine/spread/articles.py:61: 3622: Found: {'text_object_name': '248d-5899-b8ca-ac2bd8233755', 'url': 'http://blog.alunduil.com/posts/an-explanation-of-lvm-snapshots.html', 'created_at': datetime.datetime(2013, 8, 7, 20, 25, 41, 596627), 'text_container_name': '44d85795', 'etag': 'bf6285d832a356e1bf509a63edc8870f', '_id': '44d85795248d5899b8caac2bd8233755', 'parsed_at': datetime.datetime(2013, 8, 7, 20, 25, 41, 596627), 'size': 31052}
/home/alunduil/Projects/savvy/margarine/margarine/spread/articles.py:68: 3622: article: {u'created_at': {u'$date': 1375907141596}, u'parsed_at': {u'$date': 1375907141596}}
/home/alunduil/Projects/savvy/margarine/margarine/spread/articles.py:69: 3622: _id: 44d85795248d5899b8caac2bd8233755
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
This is now blocked by #42.

**Comment by alunduil** [comment]
Merged.
