### ISSUE TITLE
JSONify datetime in Spread::Article Create—Submitted,Incomplete Test

### ISSUE THREAD

**Issue by alunduil** [alunduil/margarine#42]
```
======================================================================
ERROR: Spread::Article Create—Submitted,Incomplete
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_articles.py", line 114, in test_article_create_submitted_incomplete
    create_article_consumer(mock.MagicMock(), self.method, None, json.dumps(article))
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2013, 8, 7, 20, 25, 41, 596627) is not JSON serializable
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 11704: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 11704: mock_mask: set(['keyspace'])
test_margarine/test_unit/__init__.py:94: 11704: to_mock: set(['container', 'channel', 'collection'])
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
The message passed is now out of alignment with what is expected:

```
======================================================================
FAIL: Spread::Article Create—Submitted,Incomplete
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_margarine/test_unit/test_spread/test_articles.py", line 118, in test_article_create_submitted_incomplete
    self._validate_mocks(_id, article)
  File "test_margarine/test_unit/test_spread/test_articles.py", line 55, in _validate_mocks
    self.mock_collection.update.assert_called_once_with({ '_id': _id }, { '$set': article }, upsert = True)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 846, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 835, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: update({'_id': '44d85795248d5899b8caac2bd8233755'}, {'$set': {'url': 'http://blog.alunduil.com/posts/an-explanation-of-lvm-snapshots.html', 'created_at': datetime.datetime(2013, 8, 7, 20, 25, 41, 596627)}}, upsert=True)
Actual call: update({'_id': u'44d85795248d5899b8caac2bd8233755'}, {'$set': {u'created_at': {u'$date': 1375907141596}}}, upsert=True)
-------------------- >> begin captured logging << --------------------
test_margarine/test_unit/__init__.py:92: 9468: mocks: set(['keyspace', 'container', 'collection', 'channel'])
test_margarine/test_unit/__init__.py:93: 9468: mock_mask: set(['keyspace'])
test_margarine/test_unit/__init__.py:94: 9468: to_mock: set(['container', 'channel', 'collection'])
/home/alunduil/Projects/savvy/margarine/margarine/spread/articles.py:53: 9468: article: {u'url': u'http://blog.alunduil.com/posts/an-explanation-of-lvm-snapshots.html', u'created_at': {u'$date': 1375907141596}, u'_id': u'44d85795248d5899b8caac2bd8233755'}
/home/alunduil/Projects/savvy/margarine/margarine/spread/articles.py:61: 9468: Found: {'url': 'http://blog.alunduil.com/posts/an-explanation-of-lvm-snapshots.html', 'created_at': datetime.datetime(2013, 8, 7, 20, 25, 41, 596627), '_id': '44d85795248d5899b8caac2bd8233755'}
/home/alunduil/Projects/savvy/margarine/margarine/spread/articles.py:68: 9468: article: {u'created_at': {u'$date': 1375907141596}}
/home/alunduil/Projects/savvy/margarine/margarine/spread/articles.py:69: 9468: _id: 44d85795248d5899b8caac2bd8233755
--------------------- >> end captured logging << ---------------------
```

**Comment by alunduil** [comment]
Looks like this one is ready for review.  The assumptions in the test needed to change slightly but it's much cleaner at this point and has a little bit better of logging.  The things that need to be reviewed are the following:
- Code cleanliness and readability
- Test accuracy for the story
- Logging is appropriately verbose for each level
- The test does pass but are there any unseen affects
- Is the code separation in the consumer clear
