### ISSUE TITLE
Vagrant run fails

### ISSUE THREAD

**Issue by chrisjjackson** [alunduil/margarine#54]
Running #vagrant up on  a fresh install fails at the tinge installation regarding the chef-run.

Details:

```
[tinge] Importing base box 'precise64'...
[tinge] Matching MAC address for NAT networking...
[tinge] Setting the name of the VM...
[tinge] Clearing any previously set forwarded ports...
[tinge] The cookbook path '/Users/chris.jackson/code/margarine/chef/data_bags' doesn't exist. Ignoring...
[Berkshelf] This version of the Berkshelf plugin has not been fully tested on this version of Vagrant.
[Berkshelf] You should check for a newer version of vagrant-berkshelf.
[Berkshelf] If you encounter any errors with this version, please report them at https://github.com/RiotGames/vagrant-berkshelf/issues
[Berkshelf] You can also join the discussion in #berkshelf on Freenode.
[Berkshelf] Updating Vagrant's berkshelf: '/Users/chris.jackson/.berkshelf/token_store/vagrant/berkshelf-20131216-96099-vx93uk-tinge'
[Berkshelf] Using apt (2.3.0)
[Berkshelf] Installing chef-solo-search (0.5.1) from git: 'git://github.com/edelight/chef-solo-search.git' with branch: 'master' at ref: '681f78a108f5f8a3655551b32d9939603628c568'
[Berkshelf] Using rabbitmq (2.3.2)
[Berkshelf] Using build-essential (1.4.2)
[Berkshelf] Installing mongodb (0.14.2) from git: 'https://github.com/raxsavvy/chef-mongodb.git' with branch: 'master' at ref: '6541d44ba4f55519add20745e95ce03c6ab4a91a'
[Berkshelf] Installing margarine (2.1.10) from git: 'https://github.com/raxsavvy/margarine-chef.git' with branch: 'master' at ref: 'f7b0d48d691114eb379d061e6baa848d0118ae04'
[Berkshelf] Using erlang (1.4.0)
[Berkshelf] Using yum (3.0.0)
[Berkshelf] Using yum-epel (0.2.0)
[Berkshelf] Using yum-erlang_solutions (0.1.4)
[Berkshelf] Using firewall (0.11.2)
[Berkshelf] Using python (1.4.4)
[tinge] Fixed port collision for 22 => 2202. Now on port 2203.
[tinge] Clearing any previously set network interfaces...
[tinge] Preparing network interfaces based on configuration...
[tinge] Forwarding ports...
[tinge] -- 22 => 2203 (adapter 1)
[tinge] Booting VM...
[tinge] Waiting for machine to boot. This may take a few minutes...
[tinge] Machine booted and ready!
[tinge] Configuring and enabling network interfaces...
[tinge] Mounting shared folders...
[tinge] -- /vagrant
[tinge] -- /tmp/vagrant-chef-3/chef-solo-2/roles
[tinge] -- /tmp/vagrant-chef-3/chef-solo-1/cookbooks
[tinge] -- /tmp/vagrant-chef-3/chef-solo-3/environments
[tinge] Installing Chef 11.8.2 Omnibus package...
[tinge] Downloading Chef 11.8.2 for ubuntu...
[tinge] downloading https://www.opscode.com/chef/metadata?v=11.8.2&prerelease=false&p=ubuntu&pv=12.04&m=x86_64
[tinge]   to file /tmp/install.sh.1242/metadata.txt
[tinge] trying wget...
[tinge] url https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef_11.8.2-1.ubuntu.12.04_amd64.deb
md5 3d3b3662830a44eeec71aadc098a4018
sha256  a5b00a24e68e29a01c7ab9de5cdaf0cc9fd1c889599ad9af70293e5b4de8615c
[tinge] downloaded metadata file looks valid...
[tinge] downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef_11.8.2-1.ubuntu.12.04_amd64.deb
  to file /tmp/install.sh.1242/chef_11.8.2_amd64.deb
[tinge] trying wget...
[tinge] Checksum compare with sha256sum succeeded.
[tinge] Installing Chef 11.8.2
installing with dpkg...
[tinge] Selecting previously unselected package chef.
(Reading database ...
[tinge] 51095 files and directories currently installed.)
[tinge] Unpacking chef (from .../chef_11.8.2_amd64.deb) ...
[tinge] Setting up chef (11.8.2-1.ubuntu.12.04) ...
[tinge] Thank you for installing Chef!
[tinge] Running provisioner: chef_solo...
Generating chef JSON and uploading...
Running chef-solo...
stdin: is not a tty
[2013-12-16T18:35:38+00:00] INFO: Forking chef instance to converge...
[2013-12-16T18:35:38+00:00] INFO: *** Chef 11.8.2 ***
[2013-12-16T18:35:38+00:00] INFO: Chef-client pid: 1401
[2013-12-16T18:35:38+00:00] INFO: Setting the run_list to ["role[tinge]"] from JSON
[2013-12-16T18:35:38+00:00] INFO: Run List is [role[tinge]]
[2013-12-16T18:35:38+00:00] INFO: Run List expands to [chef-solo-search, apt, margarine::tinge]
[2013-12-16T18:35:38+00:00] INFO: Starting Chef Run for tinge
[2013-12-16T18:35:38+00:00] INFO: Running start handlers
[2013-12-16T18:35:38+00:00] INFO: Start handlers complete.
[2013-12-16T18:35:42+00:00] ERROR: Failed to list data bag items in data bag: "margarine_loggers"
[2013-12-16T18:35:42+00:00] ERROR: Running exception handlers
[2013-12-16T18:35:42+00:00] ERROR: Exception handlers complete
[2013-12-16T18:35:42+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-12-16T18:35:42+00:00] ERROR: can't convert Array into String

================================================================================
Recipe Compile Error in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/margarine/recipes/tinge.rb
================================================================================


TypeError
---------
can't convert Array into String


Cookbook Trace:
---------------
  /tmp/vagrant-chef-3/chef-solo-1/cookbooks/chef-solo-search/libraries/search/overrides.rb:91:in `search_data_bag'
  /tmp/vagrant-chef-3/chef-solo-1/cookbooks/chef-solo-search/libraries/search/overrides.rb:48:in `search'
  /tmp/vagrant-chef-3/chef-solo-1/cookbooks/chef-solo-search/libraries/search.rb:69:in `search'
  /tmp/vagrant-chef-3/chef-solo-1/cookbooks/margarine/recipes/logging.rb:46:in `from_file'
  /tmp/vagrant-chef-3/chef-solo-1/cookbooks/margarine/recipes/configure.rb:41:in `from_file'
  /tmp/vagrant-chef-3/chef-solo-1/cookbooks/margarine/recipes/tinge.rb:24:in `from_file'


Relevant File Content:
----------------------
/tmp/vagrant-chef-3/chef-solo-1/cookbooks/chef-solo-search/libraries/search/overrides.rb:

 84:          end
 85:        end
 86:        return _result
 87:      end
 88:
 89:      def search_data_bag(_query, bag_name, start, rows, &block)
 90:        _result = []
 91>>       data_bag(bag_name.to_s).each do |bag_item_id|
 92:          bag_item = data_bag_item(bag_name.to_s, bag_item_id)
 93:          if _query.match(bag_item)
 94:            _result << bag_item
 95:          end
 96:        end
 97:        return _result
 98:      end
 99:    end
100:  end



[2013-12-16T18:35:38+00:00] INFO: Forking chef instance to converge...
[2013-12-16T18:35:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by alunduil** [comment]
Hey @chrisjackson1982,

I'm still trying to figure out how to handle the required empty directories for chef in vagrant with git not tracking empty directories.  My vote will probably be for adding a `.keep` empty file to directories that need to exist regardless.

For this issue, you should be able to `mkdir chef/data_bags` and all will work but if not, let me know.  If this does solve the issue, we'll add the `.keep` file after a giant merge I plan on doing this week.

**Comment by chrisjjackson** [comment]
Thanks @alunduil this workaround has fixed the issue - I'll keep an eye out for the permanent fix.
