### ISSUE TITLE
can't update user info

### ISSUE THREAD

**Issue by jruels** [alunduil/margarine#6]
https://jira.mongodb.org/browse/SERVER-9074

---

Traceback (most recent call last):
  File "/srv/www/margarine/bin/spread", line 11, in <module>
    margarine.consumers.main()
  File "/srv/www/margarine/margarine/consumers/**init**.py", line 35, in main
    users.register(channel)
  File "/srv/www/margarine/margarine/consumers/users.py", line 126, in register
    channel.basic_consume(update_user_consumer, queue = "margarine.users.update", no_ack = False, consumer_tag = "user.update")
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 219, in basic_consume
    {'consumer_tag': consumer_tag})])
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1000, in _rpc
    self._wait_on_response(method_frame))
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1026, in _send_method
    self.connection.process_data_events()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 168, in process_data_events
    if self._handle_read():
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 272, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 318, in _handle_read
    self._on_data_available(data)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1148, in _on_data_available
    self._process_frame(frame_value)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1227, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 855, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 790, in _handle_content_frame
    self._on_deliver(*response)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 885, in _on_deliver
    body)
  File "/srv/www/margarine/margarine/consumers/users.py", line 57, in update_user_consumer
    get_collection("users").update({ "username": user.pop("original_username") }, { "$set": user }, upsert = True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 479, in update
    check_keys, self.__uuid_subtype), safe)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 920, in _send_message
    rv = self.__check_response_to_last_error(response)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 863, in __check_response_to_last_error
    raise OperationFailure(details["err"], details["code"])
pymongo.errors.OperationFailure: Can't modify shard key's value. field: username: "oscon1" collection: production.users

**Comment by jruels** [comment]
Created atx user and updated name to "Fabio". 

curl -v -X GET http://api.margarine.raxsavvy.com/v1/users/atx1 2>%1
"{u'username': u'atx1', u'_id': ObjectId('51f72223c90e3867c293a171'), u'email': u'jasonruels@gmail.com', u'name': u'Fabio Lanzoni'}"

**Comment by alunduil** [comment]
Merged to master.
